services:
  - type: web
    name: student-activity-platform
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: NODE_ENV=production node dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false