services:
  - type: web
    name: student-activity-platform
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: student-activity-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://student-activity-platform.onrender.com

databases:
  - name: student-activity-db
    databaseName: student_activity_platform
    user: admin
    region: oregon
    plan: free